# https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a

# Prevent codecov from commenting
comment: false

coverage:
  precision: 2
  round: down

  status:
    project:
      default:
        against: parent
        target: auto
        branches:
          - master

    patch:
      default:
        against: parent
        target: 80%

ignore:
- "**/setup.py"
- "*/pmdarima/__check_build/*"
- "*/pmdarima/_build_utils/*"
- "*/pmdarima/_config.py"
- "*/pmdarima/__init__.py"
- "*/pmdarima/compat/matplotlib.py"
- "*/pmdarima/utils/tests/test_vis.py"
- "*/pmdarima/utils/visualization.py"
