name: Bug Report
description: Create a bug report to help us improve pmdarima
labels: [':beetle: : bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug! Please fill in the below information in as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: |
        <details closed><summary>Instructions to get necessary versions</summary>
        <p>

        Please run the following snippet and paste the output below.

        ```python
        import pmdarima; pmdarima.show_versions()

        # For pmdarima versions <1.5.2 use this:
        import platform; print(platform.platform())
        import sys; print("Python", sys.version)
        import pmdarima; print("pmdarima", pmdarima.__version__)
        import numpy; print("NumPy", numpy.__version__)
        import scipy; print("SciPy", scipy.__version__)
        import sklearn; print("Scikit-Learn", sklearn.__version__)
        import statsmodels; print("Statsmodels", statsmodels.__version__)
        ```

        </p>
        </details
      placeholder: |
        See drop down above for instructions on retrieving the versions necessary for debugging. These will be
        automatically converted to code, so no need for back ticks
      render: shell
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
