name: Question for Maintainers
description: Ask a question about pmdarima
labels: [':grey_question: : question']
body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, please consult our closed issues and docs to see
        if we have already addressed it:

        - [Closed Issues](https://github.com/alkaline-ml/pmdarima/issues?q=is%3Aissue+is%3Aclosed)
        - [Documentation](https://www.alkaline-ml.com/pmdarima/)
  - type: textarea
    id: question
    attributes:
      label: Describe the question you have
      description: A clear and concise description of the issue you're experiencing, and under what conditions.
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Versions (if necessary)
      description: |
        <details closed><summary>Instructions to get necessary versions</summary>
        <p>

        Please run the following snippet and paste the output below.

        ```python
        import pmdarima; pmdarima.show_versions()

        # For pmdarima versions <1.5.2 use this:
        import platform; print(platform.platform())
        import sys; print("Python", sys.version)
        import pmdarima; print("pmdarima", pmdarima.__version__)
        import numpy; print("NumPy", numpy.__version__)
        import scipy; print("SciPy", scipy.__version__)
        import sklearn; print("Scikit-Learn", sklearn.__version__)
        import statsmodels; print("Statsmodels", statsmodels.__version__)
        ```

        </p>
        </details
      placeholder: |
        See drop down above for instructions on retrieving the versions necessary for answering your question. These
        will be automatically converted to code, so no need for back ticks
      render: shell
    validations:
      required: false
