# Have to put the version condition on every step in here, because we can't set conditions on a template
steps:
- script: |
    call activate base
    conda install conda-build --yes
  condition: in(variables['python.version'], '3.6', '3.7')
  displayName: 'Installing conda-build'

- script: |
    call activate base
    conda info
  condition: in(variables['python.version'], '3.6', '3.7')
  displayName: 'Debug info'

- script: set CONDA_FORCE_32BIT=1
  condition: eq(variables['architecture'], 'x86')
  displayName: 'Setting conda architecture'

- script: |
    call activate base
    conda-build --python=$(python.version) conda/
  condition: in(variables['python.version'], '3.6', '3.7')
  displayName: 'Building and testing conda distribution'
