steps:
- bash: |
    pip install jinja2
    mkdir conda
    cd build_tools/azure/conda_scripts
    python render_meta.py
    cd -
  displayName: 'Rendering meta.yml file'

- powershell: ls $CONDA\Scripts
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  displayName: 'Test'

- script: conda install conda-build --yes
  displayName: 'Installing conda-build'

- script: conda-build --python=$(python.version) conda/
  displayName: 'Building and testing conda distribution'
