# Have to put the version condition on every step in here, because we can't set conditions on a template
steps:
- script: pip install jinja2
  condition: in(variables['python.version'], '3.6', '3.7')
  displayName: 'Installing Jinja'

- bash: |
    mkdir conda
    cd build_tools/azure/conda_scripts
    python render_meta.py
    cd -
  condition: in(variables['python.version'], '3.6', '3.7')
  displayName: 'Rendering meta.yml file'

- script: |
    call activate base
    conda install conda-build --yes
  condition: in(variables['python.version'], '3.6', '3.7')
  displayName: 'Installing conda-build'

- script: |
    call activate base
    conda info
  condition: in(variables['python.version'], '3.6', '3.7')
  displayName: 'Debug info'

- script: |
    call activate base
    conda-build --python=$(python.version) conda/
  condition: in(variables['python.version'], '3.6', '3.7')
  displayName: 'Building and testing conda distribution'
