steps:
- script: pip install jinja2
  displayName: 'Installing Jinja'

- bash: |
    mkdir conda
    cd build_tools/azure/conda_scripts
    python render_meta.py
    cd -
  displayName: 'Rendering meta.yml file'

- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: 'Add conda to PATH'

- bash: conda install conda-build --yes
  displayName: 'Installing conda-build'

- script: sudo chmod -R 777 /usr/local/miniconda/pkgs
  displayName: 'Fix for conda error on macOS'
  condition: eq(variables['Agent.OS'], 'Darwin')

- script: conda-build conda/
  displayName: 'Building and testing conda distribution'
