steps:
- bash: |
    pip install jinja2
    mkdir conda
    cd build_tools/azure/conda_scripts
    python render_meta.py
    cd -
  displayName: 'Rendering meta.yml file'

- script: conda init cmd.exe
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  displayName: 'Initialize conda'

- script: conda install conda-build --yes
  displayName: 'Installing conda-build'

- script: conda create -n buildenv python=$(python.version) --yes
  displayName: 'Creating conda environment'

- script: |
    call activate base
    call activate buildenv
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  displayName: 'Activating conda environment (Windows)'

- bash: source activate buildenv
  condition: eq(variables['Agent.OS'], 'Darwin')
  displayName: 'Activating conda environment (macOS)'

- script: conda-build --python=$(python.version) conda/
  displayName: 'Building and testing conda distribution'
