steps:
- script: pip install jinja2
  displayName: 'Installing Jinja'

- bash: |
    mkdir conda
    cd build_tools/azure/conda_scripts
    python render_meta.py
    cd -
  displayName: 'Rendering meta.yml file'

- script: conda install conda-build --yes
  displayName: 'Installing conda-build'

- bash: |
    conda create -n buildenv python=$(python.version)
    conda activate buildenv
  displayName: 'Creating conda environment'

- script: conda-build conda/
  displayName: 'Building and testing conda distribution'
