steps:
- bash: |
    pip install jinja2
    mkdir conda
    cd build_tools/azure/conda_scripts
    python render_meta.py
    cd -
  displayName: 'Rendering meta.yml file'

- script: conda install conda-build --yes
  displayName: 'Installing conda-build'

- script: conda-build --python=$(python.version) conda/
  displayName: 'Building and testing conda distribution'
