steps:
- bash: |
    pip install jinja2
    mkdir conda
    cd build_tools/azure/conda_scripts
    python render_meta.py
    cd -
  displayName: 'Rendering meta.yml file'

- task: CondaEnvironment@1
  inputs:
#    createCustomEnvironment: true # Optional
    environmentName: 'buildenv'
    packageSpecs: 'python=$(python.version)'
    updateConda: true
#    installOptions: 'conda-build' # Optional
    #createOptions: # Optional
    #cleanEnvironment: # Optional
  displayName: 'Creating conda environment'

- script: conda install conda-build --yes
  displayName: 'Installing conda-build'

#- script: conda create -n buildenv python=$(python.version) --yes
#  displayName: 'Creating conda environment'
#
#- script: call activate buildenv
#  condition: eq(variables['Agent.OS'], 'Windows_NT')
#  displayName: 'Activating conda environment (Windows)'
#
#- bash: source activate buildenv
#  condition: eq(variables['Agent.OS'], 'Darwin')
#  displayName: 'Activating conda environment (macOS)'

- script: conda-build --python=$(python.version) conda/
  displayName: 'Building and testing conda distribution'
