jobs:
- job: Conda
  strategy:
    # Our dependencies only support 64-bit 3.6+, so that is all we support
    matrix:
      Linux-36:
        os: 'ubuntu-18.04'
        python.version: '3.6'
        architecture: 'x64'

      Linux-37:
        os: 'ubuntu-18.04'
        python.version: '3.7'
        architecture: 'x64'

      Windows-36:
        os: 'windows-2019'
        python.version: '3.6'
        architecture: 'x64'

      Windows-37:
        os: 'windows-2019'
        python.version: '3.7'
        architecture: 'x64'

      macOS-36:
        os: 'macOS-10.14'
        python.version: '3.6'
        architecture: 'x64'

      macOS-37:
        os: 'macOS-10.14'
        python.version: '3.7'
        architecture: 'x64'

  pool:
    vmImage: '$(os)'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(architecture)'
    displayName: 'Setting Python version and system architecture'

  - template: build_and_deploy.yml

- job: test_tagging

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - bash: build_tools/azure/test_version_tagging.sh
    # Only want to run this on branches/PRs. NOT tags
    condition: not(contains(variables['Build.SourceBranch'], 'tags'))
    displayName: 'Testing git tag logic'
