parameters:
  architecture: 'x64'  # default

jobs:
- job: ${{ parameters.name }}

  pool:
    vmImage: ${{ parameters.vmImage }}  # windows-latest does not have the Microsoft Visual C++ 14.0 dependency we need

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ paremeters.python.version }}
      architecture: ${{ parameters.architecture }}
    displayName: 'Setting Python version and system architecture'

  - template: pypi/build_and_deploy.yml
  - template: conda/preprocess.yml
  # Windows gets its own template because we apparently have to activate our conda environment before _every_ step:
  # https://github.com/MicrosoftDocs/pipelines-anaconda/blob/3cf8252785ea2c873cc9c20e676b14f7b48f35ce/azure-pipelines.yml#L79-L86
  - ${{ if eq(variables['os'], 'Windows') }}
    - template: conda/build_and_deploy_windows.yml

  - ${{ if eq(variables['os'], 'macOS') }}
    - template: conda/build_and_deploy_mac.yml