parameters:
  build_conda: false

jobs:
- job: ${{ parameters.name }}

  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    build_conda: ${{ parameters.build_conda }}

  steps:
  - ${{ if eq(parameters.build_conda, 'true') }}
    - script: echo "We would build conda"