jobs:
- job: ${{ parameters.name }}

  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - ${{ if eq(parameters.vmImage, 'vs2017-win2016') }}
    - script: echo "Hello from windows"
  - ${{ if eq(parameters.vmImage, 'macOS-latest') }}
    - script: echo "Hello from mac"