jobs:
  - job: ${{ parameters.name }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    variables:
      ${{ insert }}: ${{ parameters.variables }}

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: '$(architecture)'
      displayName: 'Setting Python version and system architecture'

    # Build for PyPI if necessary
    - ${{ if eq(parameters.build_pypi, 'true') }}:
      - template: pypi/build.yml

    # Build for conda if necessary
    - ${{ if eq(parameters.build_conda, 'true') }}:
      - template: conda/preprocess.yml

      - ${{ if contains(parameters.vmImage, 'win') }}:
        - template: conda/build_windows.yml

      - ${{ if contains(parameters.vmImage, 'mac') }}:
        - template: conda/build_mac.yml

    # Always run the deploy step (it will check for tags)
    - template: pypi/deploy.yml
