parameters:
  architecture: 'x64'  # Default (for macOS builds)

jobs:
  - job: ${{ parameters.name }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    steps:
    - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(parameters.python.version)'
          architecture: '$(parameters.architecture)'
        displayName: 'Setting Python version and system architecture'

    # Always build for PyPI
    - template: pypi/build.yml

    # Build for conda if necessary
    - ${{ if eq(parameters.build_conda, 'true') }}:
      - template: conda/preprocess.yml
      - template: conda/build_windows.yml

    # Always run the deploy step (it will check for tags)
    - template: deploy.yml