jobs:
  - job: ${{ parameters.name }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    variables:
      ${{ insert }}: ${{ parameters.variables }}

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: '$(architecture)'
      displayName: 'Setting Python version and system architecture'

    # Always build for PyPI
    - template: pypi/build.yml

    # Build for conda if specified, AND only if this is a deploy or a PR (to save time)
    - ${{ if and(eq(parameters.build_conda, 'true'), or(eq(variables['Build.Reason'], 'PullRequest'), contains(variables['Build.SourceBranch'], 'tags'))) }}:
      - template: conda/preprocess.yml

      - ${{ if contains(parameters.vmImage, 'win') }}:
        - template: conda/build_windows.yml

      - ${{ if contains(parameters.vmImage, 'mac') }}:
          - template: conda/build_mac.yml

    # Only deploy for tags
    - ${{ if contains(variables['Build.SourceBranch'], 'tags') }}:
      - template: pypi/deploy.yml

