{% set data = load_setup_py_data() %}

package:
  name: 'pmdarima'
  version: "{{ data.get('version') }}"


source:
  path: ../

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - numpy>=1.16
    - {{ compiler('c') }}

  host:
    - pip
    - {{ PYTHON }}
    - Cython>=0.29
    - joblib>=0.11
    - numpy>=1.16
    - pandas>=0.19
    - scikit-learn>=0.19
    - scipy>=1.3
    - six>=1.5
    - statsmodels>=0.10.0

  run:
    - pip
    - {{ PYTHON }}
    - Cython>=0.29
    - joblib>=0.11
    - numpy>=1.16
    - pandas>=0.19
    - scikit-learn>=0.19
    - scipy>=1.3
    - six>=1.5
    - statsmodels>=0.10.0

test:
  imports:
    - pmdarima

about:
  home: https://github.com/tgsmith61591/pmdarima
  license: MIT
  license_file: LICENSE
  summary: Python's forecast::auto.arima equivalent

extra:
  maintainers:
    - Taylor G. Smith