steps:
- script: python -m pip install --upgrade pip
  displayName: 'Updating pip'

- script: |
    pip install -r requirements.txt
    pip install -r build_tools/azure/requirements.txt
  displayName: 'Installing requirements'

- script: python setup.py bdist_wheel
  displayName: 'Building wheel'

- script: pip install --pre --no-index --find-links dist/ pmdarima
  displayName: 'Installing generated wheel'

- script: pytest --showlocals --durations=20 --mpl --mpl-baseline-path=etc/pytest_images --pyargs pmdarima --benchmark-skip
  displayName: 'Running unit tests'

# We build the source archive separately because of this: https://github.com/tgsmith61591/pmdarima/pull/136#discussion_r279781731
- script: python setup.py sdist
  displayName: 'Building source archive'

- bash: |
    if python -c "from twine.commands.check import check; check(['dist/*'])" | grep  "warning"; then
        echo "README will not render properly on PyPI"
        exit 1
    else
        echo "README rendered appropriately"
    fi
  displayName: 'Checking README compatibility'
