name: Build, test, and deploy to Conda

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  build-and-deploy:
    strategy:
      fail-fast: false  # Just for debugging
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.5', '3.6', '3.7']
        architecture: ['x64']  # Conda doesn't support 32-bit, but this is more flexible than hard-coding later on
    runs-on: ${{ matrix.os }}
    steps:
      # This LOOKS like it is checking out 'master', but it is using the 'master' version of the checkout action
      # It is actually checking out the most recent version on this branch
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Add $CONDA to $PATH
        run: |
          if [ "${{ matrix.os }}" != "windows-latest" ]; then
            echo ::add-path::$CONDA/condabin
          else
            echo ::add-path::$CONDA\conda.bat
          fi
        shell: bash

      - name: Generating VERSION file
        run: python build_tools/get_tag.py

      - name: Render Conda meta.yaml file
        run: |
          pip install jinja2
          cd build_tools/github
          python render_meta.py
          cd -
        shell: bash

      # This step requires 'sudo' for mac
      - name: Installing conda-build and anaconda-client
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            sudo conda install -y anaconda-client conda-build
          else
            conda install -y anaconda-client conda-build
          fi
          conda init bash
        shell: bash

      - name: Build and test Conda package
        run: |
          conda activate base
          conda-build --python=${{ matrix.python-version }} conda/
        shell: bash

      - name: Deploy to Anaconda
        if: github.event_name == 'tag' && success()
        run: echo "This would deploy..."
        shell: bash