name: Build, test, and deploy to Conda

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.5', '3.6', '3.7']
        architecture: 'x64'  # Conda doesn't support 32-bit, but this is more flexible than hard-coding later on
    runs-on: ${{ matrix.os }}
    steps:
      # This LOOKS like it is checking out 'master', but it is using the 'master' version of the checkout action
      # It is actually checking out the most recent version on this branch
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: $${{ matrix.architecture }}
      - name: Confirm Versions
        run: python -c 'import sys; print(sys.platform, "\n", sys.version)'